services:
  pypipe:
    image: agalbulescu/pypipe:latest
    container_name: pypipe
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GITLAB_API_URL=https://gitlab.mydomain.com/api/v4
      - GITLAB_PROJECT_ID=123
      - GITLAB_ACCESS_TOKEN=this-is-the-access-token
      - GITLAB_PIPELINE_TRIGGER_TOKEN=this-is-the-trigger-token
      - GITLAB_PUBLIC_YML_ACCESS_TOKEN=a-very-long-string
    restart: unless-stopped
    network_mode: bridge  # Explicitly using the default bridge network
